
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: fyp-app
        working_dir: /var/www
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: fyp
            MYSQL_ROOT_PASSWORD: rhgb5463547gfd
            MYSQL_USER: nassor
            MYSQL_PASSWORD: nasTy63%!
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    queue:
        build:
            context: .
        container_name: laravel_queue
        working_dir: /var/www
        command: php artisan queue:work --verbose --tries=3 --timeout=90
        volumes:
            - .:/var/www
        depends_on:
            - app
        restart: unless-stopped

volumes:
    dbdata:
