
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: rhgb5463547gfd
            MYSQL_USER: nassor
            MYSQL_PASSWORD: nasTy63%!
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
